name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    paths:
    - '!artifacts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Make all targets
        run: |
          make generate

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifacts

      - name: Commit artifacts
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "actions@github.com"
          git add -f artifacts/open-traffic-generator-port.txt
          git add -f artifacts/open-traffic-generator-bgp.txt
          git add -f artifacts/open-traffic-generator-isis.txt
          git add -f artifacts/open-traffic-generator-flow.txt
          git add -f artifacts/open-traffic-generator-discovery.txt
          if git status --porcelain | grep .
            then
              git commit -m "Update auto generated content"
              git push
            else
              echo "No changed auto generated content"
          fi
