name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    paths:
    - '!artifacts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint Models
        run: |
          make lint

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifacts

      - name: Commit artifacts
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "actions@github.com"
          for MODEL in `find artifacts -type f`; do
            if [ `wc -c < $MODEL` != 0 ]; then
              git add --force $MODEL
            fi
          done
          if git status --porcelain | grep .
            then
              git commit -m "Update auto generated content"
              git push
            else
              echo "No changed auto generated content"
          fi
